/**
 * Auto-generated prior table from 1310 games (5 players, strategy: mcs).
 * Generated by scripts/build-prior-table.ts — do not edit manually.
 */

export interface CardPrior {
  card: number;
  overflowRate: number;
  rowPickRate: number;
  avgOverflowPenalty: number;
  avgRowPickPenalty: number;
  avgOverflowGap: number;
  expectedPenalty: number;
  avgTurn: number;
}

export interface TurnBaseline {
  turn: number;
  avgMinRowTop: number;
  minRowTopP50: number;
  avgPrimedRows: number;
  avgMaxRowLen: number;
}

/** Per-card prior statistics (index 0 = card 1, index 103 = card 104). */
export const CARD_PRIOR: readonly CardPrior[] = [
  { card: 1, overflowRate: 0.0000, rowPickRate: 1.0000, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 1.7701, avgOverflowGap: 0.0000, expectedPenalty: 1.7701, avgTurn: 5.1407 },
  { card: 2, overflowRate: 0.0000, rowPickRate: 0.8462, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 1.9896, avgOverflowGap: 0.0000, expectedPenalty: 1.6837, avgTurn: 5.2943 },
  { card: 3, overflowRate: 0.0000, rowPickRate: 0.7318, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.0534, avgOverflowGap: 0.0000, expectedPenalty: 1.5028, avgTurn: 5.3416 },
  { card: 4, overflowRate: 0.0000, rowPickRate: 0.6468, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.1229, avgOverflowGap: 0.0000, expectedPenalty: 1.3730, avgTurn: 5.3438 },
  { card: 5, overflowRate: 0.0000, rowPickRate: 0.5755, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.2548, avgOverflowGap: 0.0000, expectedPenalty: 1.2977, avgTurn: 5.4261 },
  { card: 6, overflowRate: 0.0000, rowPickRate: 0.5139, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.3297, avgOverflowGap: 0.0000, expectedPenalty: 1.1972, avgTurn: 5.3810 },
  { card: 7, overflowRate: 0.0004, rowPickRate: 0.4569, avgOverflowPenalty: 6.0000, avgRowPickPenalty: 2.4956, avgOverflowGap: 2.0000, expectedPenalty: 1.1427, avgTurn: 5.4290 },
  { card: 8, overflowRate: 0.0008, rowPickRate: 0.4301, avgOverflowPenalty: 5.5000, avgRowPickPenalty: 2.7123, avgOverflowGap: 4.0000, expectedPenalty: 1.1709, avgTurn: 5.5502 },
  { card: 9, overflowRate: 0.0008, rowPickRate: 0.3685, avgOverflowPenalty: 6.0000, avgRowPickPenalty: 2.7752, avgOverflowGap: 4.5000, expectedPenalty: 1.0275, avgTurn: 5.5612 },
  { card: 10, overflowRate: 0.0032, rowPickRate: 0.3563, avgOverflowPenalty: 5.6250, avgRowPickPenalty: 2.9413, avgOverflowGap: 4.7500, expectedPenalty: 1.0659, avgTurn: 5.5400 },
  { card: 11, overflowRate: 0.0036, rowPickRate: 0.3390, avgOverflowPenalty: 6.2222, avgRowPickPenalty: 2.8768, avgOverflowGap: 5.5556, expectedPenalty: 0.9976, avgTurn: 5.4131 },
  { card: 12, overflowRate: 0.0059, rowPickRate: 0.3143, avgOverflowPenalty: 9.3333, avgRowPickPenalty: 3.2648, avgOverflowGap: 5.1333, expectedPenalty: 1.0816, avgTurn: 5.6790 },
  { card: 13, overflowRate: 0.0086, rowPickRate: 0.3238, avgOverflowPenalty: 8.4286, avgRowPickPenalty: 3.0987, avgOverflowGap: 6.8571, expectedPenalty: 1.0758, avgTurn: 5.8541 },
  { card: 14, overflowRate: 0.0124, rowPickRate: 0.2929, avgOverflowPenalty: 7.4516, avgRowPickPenalty: 3.5574, avgOverflowGap: 7.4194, expectedPenalty: 1.1345, avgTurn: 5.8960 },
  { card: 15, overflowRate: 0.0125, rowPickRate: 0.2674, avgOverflowPenalty: 7.4839, avgRowPickPenalty: 3.6263, avgOverflowGap: 6.4516, expectedPenalty: 1.0635, avgTurn: 5.8256 },
  { card: 16, overflowRate: 0.0150, rowPickRate: 0.2562, avgOverflowPenalty: 7.0263, avgRowPickPenalty: 3.5200, avgOverflowGap: 7.0789, expectedPenalty: 1.0071, avgTurn: 5.9965 },
  { card: 17, overflowRate: 0.0217, rowPickRate: 0.2507, avgOverflowPenalty: 7.5636, avgRowPickPenalty: 3.9590, avgOverflowGap: 8.5818, expectedPenalty: 1.1570, avgTurn: 6.0886 },
  { card: 18, overflowRate: 0.0248, rowPickRate: 0.2715, avgOverflowPenalty: 7.5574, avgRowPickPenalty: 3.9865, avgOverflowGap: 8.0820, expectedPenalty: 1.2699, avgTurn: 6.1585 },
  { card: 19, overflowRate: 0.0223, rowPickRate: 0.2524, avgOverflowPenalty: 7.6964, avgRowPickPenalty: 4.0869, avgOverflowGap: 9.4464, expectedPenalty: 1.2033, avgTurn: 6.1415 },
  { card: 20, overflowRate: 0.0259, rowPickRate: 0.2221, avgOverflowPenalty: 7.0923, avgRowPickPenalty: 3.9372, avgOverflowGap: 9.2462, expectedPenalty: 1.0582, avgTurn: 5.9207 },
  { card: 21, overflowRate: 0.0301, rowPickRate: 0.2382, avgOverflowPenalty: 7.5789, avgRowPickPenalty: 4.2641, avgOverflowGap: 10.6974, expectedPenalty: 1.2438, avgTurn: 6.3684 },
  { card: 22, overflowRate: 0.0411, rowPickRate: 0.2041, avgOverflowPenalty: 7.6765, avgRowPickPenalty: 4.2387, avgOverflowGap: 10.3529, expectedPenalty: 1.1804, avgTurn: 5.6816 },
  { card: 23, overflowRate: 0.0314, rowPickRate: 0.2165, avgOverflowPenalty: 8.2564, avgRowPickPenalty: 4.3383, avgOverflowGap: 11.9359, expectedPenalty: 1.1984, avgTurn: 6.5360 },
  { card: 24, overflowRate: 0.0322, rowPickRate: 0.2130, avgOverflowPenalty: 8.2375, avgRowPickPenalty: 4.5236, avgOverflowGap: 11.1750, expectedPenalty: 1.2287, avgTurn: 6.5652 },
  { card: 25, overflowRate: 0.0399, rowPickRate: 0.2015, avgOverflowPenalty: 8.2222, avgRowPickPenalty: 4.3780, avgOverflowGap: 11.5859, expectedPenalty: 1.2104, avgTurn: 6.4587 },
  { card: 26, overflowRate: 0.0373, rowPickRate: 0.1985, avgOverflowPenalty: 7.9462, avgRowPickPenalty: 4.7253, avgOverflowGap: 12.6667, expectedPenalty: 1.2342, avgTurn: 6.6720 },
  { card: 27, overflowRate: 0.0438, rowPickRate: 0.2029, avgOverflowPenalty: 8.0463, avgRowPickPenalty: 4.6280, avgOverflowGap: 12.1667, expectedPenalty: 1.2918, avgTurn: 6.6932 },
  { card: 28, overflowRate: 0.0429, rowPickRate: 0.1875, avgOverflowPenalty: 7.7944, avgRowPickPenalty: 4.7436, avgOverflowGap: 12.5514, expectedPenalty: 1.2236, avgTurn: 6.7424 },
  { card: 29, overflowRate: 0.0460, rowPickRate: 0.1904, avgOverflowPenalty: 7.8547, avgRowPickPenalty: 4.6921, avgOverflowGap: 12.9829, expectedPenalty: 1.2549, avgTurn: 6.8273 },
  { card: 30, overflowRate: 0.0534, rowPickRate: 0.1663, avgOverflowPenalty: 7.8296, avgRowPickPenalty: 4.4310, avgOverflowGap: 14.0963, expectedPenalty: 1.1552, avgTurn: 6.3654 },
  { card: 31, overflowRate: 0.0455, rowPickRate: 0.1795, avgOverflowPenalty: 8.4174, avgRowPickPenalty: 4.6256, avgOverflowGap: 13.0348, expectedPenalty: 1.2131, avgTurn: 6.9110 },
  { card: 32, overflowRate: 0.0406, rowPickRate: 0.1721, avgOverflowPenalty: 7.9100, avgRowPickPenalty: 4.7759, avgOverflowGap: 14.6800, expectedPenalty: 1.1433, avgTurn: 6.8790 },
  { card: 33, overflowRate: 0.0556, rowPickRate: 0.1602, avgOverflowPenalty: 7.7445, avgRowPickPenalty: 4.4582, avgOverflowGap: 16.2847, expectedPenalty: 1.1448, avgTurn: 6.1055 },
  { card: 34, overflowRate: 0.0518, rowPickRate: 0.1458, avgOverflowPenalty: 8.2000, avgRowPickPenalty: 4.7951, avgOverflowGap: 15.0923, expectedPenalty: 1.1239, avgTurn: 6.9733 },
  { card: 35, overflowRate: 0.0536, rowPickRate: 0.1400, avgOverflowPenalty: 8.6716, avgRowPickPenalty: 4.6571, avgOverflowGap: 14.6642, expectedPenalty: 1.1168, avgTurn: 6.6760 },
  { card: 36, overflowRate: 0.0490, rowPickRate: 0.1417, avgOverflowPenalty: 8.5417, avgRowPickPenalty: 4.8040, avgOverflowGap: 14.4333, expectedPenalty: 1.0992, avgTurn: 6.9469 },
  { card: 37, overflowRate: 0.0575, rowPickRate: 0.1535, avgOverflowPenalty: 8.6370, avgRowPickPenalty: 4.7103, avgOverflowGap: 16.2603, expectedPenalty: 1.2197, avgTurn: 6.9839 },
  { card: 38, overflowRate: 0.0574, rowPickRate: 0.1317, avgOverflowPenalty: 8.0288, avgRowPickPenalty: 4.8213, avgOverflowGap: 17.1367, expectedPenalty: 1.0953, avgTurn: 6.9447 },
  { card: 39, overflowRate: 0.0618, rowPickRate: 0.1220, avgOverflowPenalty: 8.1579, avgRowPickPenalty: 4.7833, avgOverflowGap: 14.7237, expectedPenalty: 1.0874, avgTurn: 6.9972 },
  { card: 40, overflowRate: 0.0595, rowPickRate: 0.1308, avgOverflowPenalty: 7.8733, avgRowPickPenalty: 4.7455, avgOverflowGap: 17.3800, expectedPenalty: 1.0892, avgTurn: 6.5278 },
  { card: 41, overflowRate: 0.0481, rowPickRate: 0.1096, avgOverflowPenalty: 8.0164, avgRowPickPenalty: 4.5863, avgOverflowGap: 16.0082, expectedPenalty: 0.8881, avgTurn: 6.9358 },
  { card: 42, overflowRate: 0.0592, rowPickRate: 0.1167, avgOverflowPenalty: 8.1438, avgRowPickPenalty: 4.7500, avgOverflowGap: 17.3288, expectedPenalty: 1.0361, avgTurn: 7.0215 },
  { card: 43, overflowRate: 0.0583, rowPickRate: 0.1066, avgOverflowPenalty: 8.1438, avgRowPickPenalty: 4.8352, avgOverflowGap: 18.2671, expectedPenalty: 0.9904, avgTurn: 6.8970 },
  { card: 44, overflowRate: 0.0625, rowPickRate: 0.1155, avgOverflowPenalty: 7.8302, avgRowPickPenalty: 4.3129, avgOverflowGap: 20.8302, expectedPenalty: 0.9874, avgTurn: 6.1332 },
  { card: 45, overflowRate: 0.0664, rowPickRate: 0.0861, avgOverflowPenalty: 8.4691, avgRowPickPenalty: 4.2381, avgOverflowGap: 18.8457, expectedPenalty: 0.9278, avgTurn: 6.6612 },
  { card: 46, overflowRate: 0.0622, rowPickRate: 0.0947, avgOverflowPenalty: 8.7226, avgRowPickPenalty: 4.3602, avgOverflowGap: 17.6065, expectedPenalty: 0.9558, avgTurn: 6.7511 },
  { card: 47, overflowRate: 0.0685, rowPickRate: 0.0784, avgOverflowPenalty: 8.2733, avgRowPickPenalty: 4.5838, avgOverflowGap: 17.4826, expectedPenalty: 0.9260, avgTurn: 6.7914 },
  { card: 48, overflowRate: 0.0697, rowPickRate: 0.0824, avgOverflowPenalty: 8.3529, avgRowPickPenalty: 4.7910, avgOverflowGap: 19.1235, expectedPenalty: 0.9774, avgTurn: 6.7543 },
  { card: 49, overflowRate: 0.0700, rowPickRate: 0.0680, avgOverflowPenalty: 8.0581, avgRowPickPenalty: 4.6108, avgOverflowGap: 19.2558, expectedPenalty: 0.8775, avgTurn: 6.6931 },
  { card: 50, overflowRate: 0.0731, rowPickRate: 0.0711, avgOverflowPenalty: 8.4615, avgRowPickPenalty: 4.3898, avgOverflowGap: 21.1154, expectedPenalty: 0.9301, avgTurn: 6.3151 },
  { card: 51, overflowRate: 0.0660, rowPickRate: 0.0592, avgOverflowPenalty: 8.1879, avgRowPickPenalty: 4.4797, avgOverflowGap: 20.4121, expectedPenalty: 0.8056, avgTurn: 6.4628 },
  { card: 52, overflowRate: 0.0671, rowPickRate: 0.0623, avgOverflowPenalty: 8.2679, avgRowPickPenalty: 4.1603, avgOverflowGap: 18.8631, expectedPenalty: 0.8139, avgTurn: 6.4932 },
  { card: 53, overflowRate: 0.0672, rowPickRate: 0.0477, avgOverflowPenalty: 8.2169, avgRowPickPenalty: 4.1186, avgOverflowGap: 21.2048, expectedPenalty: 0.7484, avgTurn: 6.4284 },
  { card: 54, overflowRate: 0.0788, rowPickRate: 0.0448, avgOverflowPenalty: 8.4975, avgRowPickPenalty: 4.1429, avgOverflowGap: 21.0558, expectedPenalty: 0.8555, avgTurn: 6.3377 },
  { card: 55, overflowRate: 0.0776, rowPickRate: 0.0500, avgOverflowPenalty: 8.4772, avgRowPickPenalty: 4.0709, avgOverflowGap: 26.0203, expectedPenalty: 0.8610, avgTurn: 5.4358 },
  { card: 56, overflowRate: 0.0878, rowPickRate: 0.0404, avgOverflowPenalty: 8.6279, avgRowPickPenalty: 3.8283, avgOverflowGap: 22.0930, expectedPenalty: 0.9118, avgTurn: 6.0812 },
  { card: 57, overflowRate: 0.0768, rowPickRate: 0.0314, avgOverflowPenalty: 8.3403, avgRowPickPenalty: 3.8205, avgOverflowGap: 22.6387, expectedPenalty: 0.7600, avgTurn: 6.0687 },
  { card: 58, overflowRate: 0.0907, rowPickRate: 0.0361, avgOverflowPenalty: 8.3032, avgRowPickPenalty: 3.8182, avgOverflowGap: 23.1041, expectedPenalty: 0.8908, avgTurn: 5.9688 },
  { card: 59, overflowRate: 0.0905, rowPickRate: 0.0300, avgOverflowPenalty: 8.5874, avgRowPickPenalty: 3.4730, avgOverflowGap: 23.1614, expectedPenalty: 0.8819, avgTurn: 5.8952 },
  { card: 60, overflowRate: 0.0968, rowPickRate: 0.0300, avgOverflowPenalty: 8.9915, avgRowPickPenalty: 3.6438, avgOverflowGap: 24.7839, expectedPenalty: 0.9799, avgTurn: 5.5548 },
  { card: 61, overflowRate: 0.0926, rowPickRate: 0.0321, avgOverflowPenalty: 8.9430, avgRowPickPenalty: 3.4810, avgOverflowGap: 23.1798, expectedPenalty: 0.9399, avgTurn: 5.7027 },
  { card: 62, overflowRate: 0.0956, rowPickRate: 0.0203, avgOverflowPenalty: 8.4113, avgRowPickPenalty: 3.7959, avgOverflowGap: 25.2857, expectedPenalty: 0.8808, avgTurn: 5.6653 },
  { card: 63, overflowRate: 0.1074, rowPickRate: 0.0136, avgOverflowPenalty: 8.9033, avgRowPickPenalty: 3.1176, avgOverflowGap: 24.6580, expectedPenalty: 0.9988, avgTurn: 5.5791 },
  { card: 64, overflowRate: 0.1033, rowPickRate: 0.0138, avgOverflowPenalty: 8.5020, avgRowPickPenalty: 3.4118, avgOverflowGap: 25.4588, expectedPenalty: 0.9254, avgTurn: 5.4161 },
  { card: 65, overflowRate: 0.1094, rowPickRate: 0.0182, avgOverflowPenalty: 8.2519, avgRowPickPenalty: 2.8667, avgOverflowGap: 26.4741, expectedPenalty: 0.9546, avgTurn: 5.1470 },
  { card: 66, overflowRate: 0.1115, rowPickRate: 0.0094, avgOverflowPenalty: 8.7190, avgRowPickPenalty: 3.2174, avgOverflowGap: 27.9234, expectedPenalty: 1.0020, avgTurn: 4.7624 },
  { card: 67, overflowRate: 0.1045, rowPickRate: 0.0135, avgOverflowPenalty: 8.9490, avgRowPickPenalty: 4.0606, avgOverflowGap: 26.6392, expectedPenalty: 0.9898, avgTurn: 5.1999 },
  { card: 68, overflowRate: 0.1109, rowPickRate: 0.0135, avgOverflowPenalty: 8.9211, avgRowPickPenalty: 3.0000, avgOverflowGap: 25.8244, expectedPenalty: 1.0298, avgTurn: 5.0564 },
  { card: 69, overflowRate: 0.1126, rowPickRate: 0.0084, avgOverflowPenalty: 8.7951, avgRowPickPenalty: 2.9048, avgOverflowGap: 28.3286, expectedPenalty: 1.0147, avgTurn: 4.9140 },
  { card: 70, overflowRate: 0.1277, rowPickRate: 0.0051, avgOverflowPenalty: 8.8297, avgRowPickPenalty: 3.0000, avgOverflowGap: 27.2817, expectedPenalty: 1.1431, avgTurn: 4.7802 },
  { card: 71, overflowRate: 0.1198, rowPickRate: 0.0064, avgOverflowPenalty: 8.8933, avgRowPickPenalty: 3.7500, avgOverflowGap: 25.7267, expectedPenalty: 1.0890, avgTurn: 4.7525 },
  { card: 72, overflowRate: 0.1455, rowPickRate: 0.0045, avgOverflowPenalty: 8.7011, avgRowPickPenalty: 3.0000, avgOverflowGap: 26.8101, expectedPenalty: 1.2797, avgTurn: 4.7947 },
  { card: 73, overflowRate: 0.1325, rowPickRate: 0.0036, avgOverflowPenalty: 9.2364, avgRowPickPenalty: 1.7778, avgOverflowGap: 28.7242, expectedPenalty: 1.2300, avgTurn: 4.6877 },
  { card: 74, overflowRate: 0.1305, rowPickRate: 0.0008, avgOverflowPenalty: 8.2388, avgRowPickPenalty: 2.0000, avgOverflowGap: 26.0418, expectedPenalty: 1.0763, avgTurn: 4.7044 },
  { card: 75, overflowRate: 0.1359, rowPickRate: 0.0016, avgOverflowPenalty: 8.9273, avgRowPickPenalty: 3.2500, avgOverflowGap: 27.8750, expectedPenalty: 1.2180, avgTurn: 4.5588 },
  { card: 76, overflowRate: 0.1399, rowPickRate: 0.0020, avgOverflowPenalty: 8.2878, avgRowPickPenalty: 2.6000, avgOverflowGap: 28.6221, expectedPenalty: 1.1647, avgTurn: 4.5120 },
  { card: 77, overflowRate: 0.1370, rowPickRate: 0.0012, avgOverflowPenalty: 8.8098, avgRowPickPenalty: 4.0000, avgOverflowGap: 30.0576, expectedPenalty: 1.2121, avgTurn: 4.1896 },
  { card: 78, overflowRate: 0.1460, rowPickRate: 0.0016, avgOverflowPenalty: 9.2371, avgRowPickPenalty: 3.2500, avgOverflowGap: 28.5422, expectedPenalty: 1.3542, avgTurn: 4.4425 },
  { card: 79, overflowRate: 0.1516, rowPickRate: 0.0012, avgOverflowPenalty: 8.7203, avgRowPickPenalty: 1.6667, avgOverflowGap: 27.5303, expectedPenalty: 1.3240, avgTurn: 4.3184 },
  { card: 80, overflowRate: 0.1406, rowPickRate: 0.0004, avgOverflowPenalty: 9.0667, avgRowPickPenalty: 1.0000, avgOverflowGap: 29.1275, expectedPenalty: 1.2756, avgTurn: 4.1517 },
  { card: 81, overflowRate: 0.1586, rowPickRate: 0.0000, avgOverflowPenalty: 9.0779, avgRowPickPenalty: 0.0000, avgOverflowGap: 26.4573, expectedPenalty: 1.4400, avgTurn: 4.1259 },
  { card: 82, overflowRate: 0.1550, rowPickRate: 0.0000, avgOverflowPenalty: 9.1850, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.4250, expectedPenalty: 1.4240, avgTurn: 4.3167 },
  { card: 83, overflowRate: 0.1747, rowPickRate: 0.0000, avgOverflowPenalty: 8.9312, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.2317, expectedPenalty: 1.5601, avgTurn: 4.2957 },
  { card: 84, overflowRate: 0.1734, rowPickRate: 0.0000, avgOverflowPenalty: 9.1416, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.5594, expectedPenalty: 1.5851, avgTurn: 4.2783 },
  { card: 85, overflowRate: 0.1747, rowPickRate: 0.0000, avgOverflowPenalty: 8.9906, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.2465, expectedPenalty: 1.5710, avgTurn: 4.0652 },
  { card: 86, overflowRate: 0.1640, rowPickRate: 0.0000, avgOverflowPenalty: 9.2642, avgRowPickPenalty: 0.0000, avgOverflowGap: 25.9481, expectedPenalty: 1.5190, avgTurn: 4.1069 },
  { card: 87, overflowRate: 0.1781, rowPickRate: 0.0000, avgOverflowPenalty: 9.0977, avgRowPickPenalty: 0.0000, avgOverflowGap: 28.9864, expectedPenalty: 1.6206, avgTurn: 4.0879 },
  { card: 88, overflowRate: 0.1901, rowPickRate: 0.0000, avgOverflowPenalty: 8.8386, avgRowPickPenalty: 0.0000, avgOverflowGap: 29.1444, expectedPenalty: 1.6807, avgTurn: 3.8191 },
  { card: 89, overflowRate: 0.1871, rowPickRate: 0.0000, avgOverflowPenalty: 9.3141, avgRowPickPenalty: 0.0000, avgOverflowGap: 26.0748, expectedPenalty: 1.7422, avgTurn: 4.1003 },
  { card: 90, overflowRate: 0.1787, rowPickRate: 0.0004, avgOverflowPenalty: 8.9692, avgRowPickPenalty: 1.0000, avgOverflowGap: 24.9011, expectedPenalty: 1.6033, avgTurn: 3.9980 },
  { card: 91, overflowRate: 0.2013, rowPickRate: 0.0000, avgOverflowPenalty: 9.2717, avgRowPickPenalty: 0.0000, avgOverflowGap: 24.4764, expectedPenalty: 1.8668, avgTurn: 4.1990 },
  { card: 92, overflowRate: 0.1761, rowPickRate: 0.0000, avgOverflowPenalty: 9.2750, avgRowPickPenalty: 0.0000, avgOverflowGap: 23.4295, expectedPenalty: 1.6337, avgTurn: 4.0404 },
  { card: 93, overflowRate: 0.2112, rowPickRate: 0.0000, avgOverflowPenalty: 9.3043, avgRowPickPenalty: 0.0000, avgOverflowGap: 26.3043, expectedPenalty: 1.9651, avgTurn: 4.0839 },
  { card: 94, overflowRate: 0.2148, rowPickRate: 0.0000, avgOverflowPenalty: 9.3925, avgRowPickPenalty: 0.0000, avgOverflowGap: 23.1271, expectedPenalty: 2.0173, avgTurn: 4.1730 },
  { card: 95, overflowRate: 0.2048, rowPickRate: 0.0000, avgOverflowPenalty: 9.0977, avgRowPickPenalty: 0.0000, avgOverflowGap: 21.5098, expectedPenalty: 1.8632, avgTurn: 4.2288 },
  { card: 96, overflowRate: 0.2301, rowPickRate: 0.0000, avgOverflowPenalty: 9.0602, avgRowPickPenalty: 0.0000, avgOverflowGap: 21.1487, expectedPenalty: 2.0851, avgTurn: 4.2159 },
  { card: 97, overflowRate: 0.2172, rowPickRate: 0.0000, avgOverflowPenalty: 8.9511, avgRowPickPenalty: 0.0000, avgOverflowGap: 21.7462, expectedPenalty: 1.9445, avgTurn: 4.1793 },
  { card: 98, overflowRate: 0.2283, rowPickRate: 0.0000, avgOverflowPenalty: 9.0650, avgRowPickPenalty: 0.0000, avgOverflowGap: 20.5237, expectedPenalty: 2.0698, avgTurn: 4.2885 },
  { card: 99, overflowRate: 0.2245, rowPickRate: 0.0000, avgOverflowPenalty: 8.7831, avgRowPickPenalty: 0.0000, avgOverflowGap: 19.0741, expectedPenalty: 1.9715, avgTurn: 4.2169 },
  { card: 100, overflowRate: 0.2212, rowPickRate: 0.0000, avgOverflowPenalty: 9.5800, avgRowPickPenalty: 0.0000, avgOverflowGap: 20.3055, expectedPenalty: 2.1195, avgTurn: 4.3994 },
  { card: 101, overflowRate: 0.2322, rowPickRate: 0.0000, avgOverflowPenalty: 9.6344, avgRowPickPenalty: 0.0000, avgOverflowGap: 16.7976, expectedPenalty: 2.2374, avgTurn: 4.4100 },
  { card: 102, overflowRate: 0.2139, rowPickRate: 0.0000, avgOverflowPenalty: 9.4462, avgRowPickPenalty: 0.0000, avgOverflowGap: 17.0077, expectedPenalty: 2.0206, avgTurn: 4.5195 },
  { card: 103, overflowRate: 0.2091, rowPickRate: 0.0000, avgOverflowPenalty: 9.2314, avgRowPickPenalty: 0.0000, avgOverflowGap: 14.8910, expectedPenalty: 1.9304, avgTurn: 4.5270 },
  { card: 104, overflowRate: 0.2143, rowPickRate: 0.0000, avgOverflowPenalty: 9.3855, avgRowPickPenalty: 0.0000, avgOverflowGap: 12.8566, expectedPenalty: 2.0112, avgTurn: 4.6285 },
];

/** Per-turn board state baselines (index 0 = turn 1, index 9 = turn 10). */
export const TURN_BASELINE: readonly TurnBaseline[] = [
  { turn: 1, avgMinRowTop: 21.0828, minRowTopP50: 17, avgPrimedRows: 0.0000, avgMaxRowLen: 1.0000 },
  { turn: 2, avgMinRowTop: 21.3375, minRowTopP50: 16, avgPrimedRows: 0.2680, avgMaxRowLen: 3.6476 },
  { turn: 3, avgMinRowTop: 23.8925, minRowTopP50: 16, avgPrimedRows: 0.6895, avgMaxRowLen: 4.3036 },
  { turn: 4, avgMinRowTop: 31.9384, minRowTopP50: 22, avgPrimedRows: 1.1117, avgMaxRowLen: 4.6061 },
  { turn: 5, avgMinRowTop: 43.8279, minRowTopP50: 44, avgPrimedRows: 1.4093, avgMaxRowLen: 4.7401 },
  { turn: 6, avgMinRowTop: 49.2987, minRowTopP50: 54, avgPrimedRows: 1.6347, avgMaxRowLen: 4.7914 },
  { turn: 7, avgMinRowTop: 51.4178, minRowTopP50: 55, avgPrimedRows: 1.8171, avgMaxRowLen: 4.8273 },
  { turn: 8, avgMinRowTop: 50.2843, minRowTopP50: 52, avgPrimedRows: 1.9417, avgMaxRowLen: 4.8522 },
  { turn: 9, avgMinRowTop: 47.1335, minRowTopP50: 48, avgPrimedRows: 1.9105, avgMaxRowLen: 4.8416 },
  { turn: 10, avgMinRowTop: 42.6497, minRowTopP50: 42, avgPrimedRows: 1.7785, avgMaxRowLen: 4.8028 },
];

/** Number of games used to generate this prior. */
export const PRIOR_GAMES = 1310;
