/**
 * Auto-generated prior table from 780 games (5 players, strategy: mcs).
 * Generated by scripts/build-prior-table.ts — do not edit manually.
 */

export interface CardPrior {
  card: number;
  overflowRate: number;
  rowPickRate: number;
  avgOverflowPenalty: number;
  avgRowPickPenalty: number;
  avgOverflowGap: number;
  expectedPenalty: number;
  avgTurn: number;
}

export interface TurnBaseline {
  turn: number;
  avgMinRowTop: number;
  minRowTopP50: number;
  avgPrimedRows: number;
  avgMaxRowLen: number;
}

/** Per-card prior statistics (index 0 = card 1, index 103 = card 104). */
export const CARD_PRIOR: readonly CardPrior[] = [
  { card: 1, overflowRate: 0.0000, rowPickRate: 1.0000, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 1.7959, avgOverflowGap: 0.0000, expectedPenalty: 1.7959, avgTurn: 5.1184 },
  { card: 2, overflowRate: 0.0000, rowPickRate: 0.8528, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.0309, avgOverflowGap: 0.0000, expectedPenalty: 1.7319, avgTurn: 5.3120 },
  { card: 3, overflowRate: 0.0000, rowPickRate: 0.7403, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.0509, avgOverflowGap: 0.0000, expectedPenalty: 1.5182, avgTurn: 5.3291 },
  { card: 4, overflowRate: 0.0000, rowPickRate: 0.6401, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.1573, avgOverflowGap: 0.0000, expectedPenalty: 1.3810, avgTurn: 5.4252 },
  { card: 5, overflowRate: 0.0000, rowPickRate: 0.5746, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.2655, avgOverflowGap: 0.0000, expectedPenalty: 1.3016, avgTurn: 5.4521 },
  { card: 6, overflowRate: 0.0000, rowPickRate: 0.5074, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.3887, avgOverflowGap: 0.0000, expectedPenalty: 1.2119, avgTurn: 5.4037 },
  { card: 7, overflowRate: 0.0000, rowPickRate: 0.4644, avgOverflowPenalty: 0.0000, avgRowPickPenalty: 2.5307, avgOverflowGap: 0.0000, expectedPenalty: 1.1752, avgTurn: 5.5031 },
  { card: 8, overflowRate: 0.0007, rowPickRate: 0.4240, avgOverflowPenalty: 6.0000, avgRowPickPenalty: 2.7095, avgOverflowGap: 3.0000, expectedPenalty: 1.1528, avgTurn: 5.5949 },
  { card: 9, overflowRate: 0.0007, rowPickRate: 0.3799, avgOverflowPenalty: 6.0000, avgRowPickPenalty: 2.7176, avgOverflowGap: 3.0000, expectedPenalty: 1.0364, avgTurn: 5.6572 },
  { card: 10, overflowRate: 0.0020, rowPickRate: 0.3514, avgOverflowPenalty: 5.6667, avgRowPickPenalty: 2.9887, avgOverflowGap: 4.3333, expectedPenalty: 1.0615, avgTurn: 5.5632 },
  { card: 11, overflowRate: 0.0039, rowPickRate: 0.3445, avgOverflowPenalty: 6.1667, avgRowPickPenalty: 2.9237, avgOverflowGap: 5.1667, expectedPenalty: 1.0316, avgTurn: 5.4642 },
  { card: 12, overflowRate: 0.0067, rowPickRate: 0.3140, avgOverflowPenalty: 9.3000, avgRowPickPenalty: 3.3426, avgOverflowGap: 4.9000, expectedPenalty: 1.1116, avgTurn: 5.7368 },
  { card: 13, overflowRate: 0.0081, rowPickRate: 0.3200, avgOverflowPenalty: 8.5833, avgRowPickPenalty: 3.1123, avgOverflowGap: 6.9167, expectedPenalty: 1.0658, avgTurn: 5.8603 },
  { card: 14, overflowRate: 0.0142, rowPickRate: 0.3090, avgOverflowPenalty: 7.4762, avgRowPickPenalty: 3.4967, avgOverflowGap: 7.3810, expectedPenalty: 1.1866, avgTurn: 5.9277 },
  { card: 15, overflowRate: 0.0129, rowPickRate: 0.2734, avgOverflowPenalty: 7.5263, avgRowPickPenalty: 3.6377, avgOverflowGap: 5.8947, expectedPenalty: 1.0916, avgTurn: 5.8636 },
  { card: 16, overflowRate: 0.0143, rowPickRate: 0.2503, avgOverflowPenalty: 6.7727, avgRowPickPenalty: 3.5521, avgOverflowGap: 7.2273, expectedPenalty: 0.9863, avgTurn: 6.0117 },
  { card: 17, overflowRate: 0.0255, rowPickRate: 0.2409, avgOverflowPenalty: 7.4615, avgRowPickPenalty: 4.0867, avgOverflowGap: 8.2564, expectedPenalty: 1.1743, avgTurn: 6.0065 },
  { card: 18, overflowRate: 0.0271, rowPickRate: 0.2767, avgOverflowPenalty: 7.3000, avgRowPickPenalty: 3.8729, avgOverflowGap: 8.3500, expectedPenalty: 1.2693, avgTurn: 6.1658 },
  { card: 19, overflowRate: 0.0199, rowPickRate: 0.2473, avgOverflowPenalty: 8.1333, avgRowPickPenalty: 4.0697, avgOverflowGap: 9.6667, expectedPenalty: 1.1684, avgTurn: 6.2023 },
  { card: 20, overflowRate: 0.0230, rowPickRate: 0.2190, avgOverflowPenalty: 7.5143, avgRowPickPenalty: 3.9850, avgOverflowGap: 8.2857, expectedPenalty: 1.0452, avgTurn: 5.9685 },
  { card: 21, overflowRate: 0.0296, rowPickRate: 0.2224, avgOverflowPenalty: 7.5455, avgRowPickPenalty: 4.1545, avgOverflowGap: 10.0909, expectedPenalty: 1.1476, avgTurn: 6.3430 },
  { card: 22, overflowRate: 0.0425, rowPickRate: 0.2009, avgOverflowPenalty: 7.4603, avgRowPickPenalty: 4.3758, avgOverflowGap: 10.5714, expectedPenalty: 1.1962, avgTurn: 5.6689 },
  { card: 23, overflowRate: 0.0345, rowPickRate: 0.2098, avgOverflowPenalty: 8.1154, avgRowPickPenalty: 4.3829, avgOverflowGap: 11.8269, expectedPenalty: 1.1999, avgTurn: 6.5405 },
  { card: 24, overflowRate: 0.0354, rowPickRate: 0.2088, avgOverflowPenalty: 8.3462, avgRowPickPenalty: 4.6287, avgOverflowGap: 11.5577, expectedPenalty: 1.2619, avgTurn: 6.6014 },
  { card: 25, overflowRate: 0.0424, rowPickRate: 0.1946, avgOverflowPenalty: 8.3651, avgRowPickPenalty: 4.2561, avgOverflowGap: 12.1587, expectedPenalty: 1.1832, avgTurn: 6.4525 },
  { card: 26, overflowRate: 0.0424, rowPickRate: 0.2071, avgOverflowPenalty: 8.2698, avgRowPickPenalty: 4.7727, avgOverflowGap: 12.7937, expectedPenalty: 1.3389, avgTurn: 6.6059 },
  { card: 27, overflowRate: 0.0446, rowPickRate: 0.2107, avgOverflowPenalty: 8.0152, avgRowPickPenalty: 4.5577, avgOverflowGap: 12.2576, expectedPenalty: 1.3174, avgTurn: 6.7056 },
  { card: 28, overflowRate: 0.0429, rowPickRate: 0.1828, avgOverflowPenalty: 7.7231, avgRowPickPenalty: 4.7726, avgOverflowGap: 12.0615, expectedPenalty: 1.2040, avgTurn: 6.7617 },
  { card: 29, overflowRate: 0.0431, rowPickRate: 0.1865, avgOverflowPenalty: 7.8769, avgRowPickPenalty: 4.5623, avgOverflowGap: 12.4615, expectedPenalty: 1.1904, avgTurn: 6.7711 },
  { card: 30, overflowRate: 0.0511, rowPickRate: 0.1667, avgOverflowPenalty: 8.0130, avgRowPickPenalty: 4.6016, avgOverflowGap: 13.3117, expectedPenalty: 1.1766, avgTurn: 6.3918 },
  { card: 31, overflowRate: 0.0394, rowPickRate: 0.1834, avgOverflowPenalty: 8.6667, avgRowPickPenalty: 4.7419, avgOverflowGap: 13.0333, expectedPenalty: 1.2117, avgTurn: 6.9882 },
  { card: 32, overflowRate: 0.0388, rowPickRate: 0.1714, avgOverflowPenalty: 8.0345, avgRowPickPenalty: 4.7227, avgOverflowGap: 13.8448, expectedPenalty: 1.1212, avgTurn: 6.8581 },
  { card: 33, overflowRate: 0.0531, rowPickRate: 0.1642, avgOverflowPenalty: 7.8333, avgRowPickPenalty: 4.6390, avgOverflowGap: 16.2436, expectedPenalty: 1.1778, avgTurn: 6.1396 },
  { card: 34, overflowRate: 0.0591, rowPickRate: 0.1514, avgOverflowPenalty: 8.3034, avgRowPickPenalty: 4.9035, avgOverflowGap: 15.7191, expectedPenalty: 1.2331, avgTurn: 6.9329 },
  { card: 35, overflowRate: 0.0547, rowPickRate: 0.1372, avgOverflowPenalty: 8.7160, avgRowPickPenalty: 4.6158, avgOverflowGap: 14.8025, expectedPenalty: 1.1101, avgTurn: 6.6459 },
  { card: 36, overflowRate: 0.0547, rowPickRate: 0.1309, avgOverflowPenalty: 8.4444, avgRowPickPenalty: 4.9433, avgOverflowGap: 14.2963, expectedPenalty: 1.1086, avgTurn: 6.9507 },
  { card: 37, overflowRate: 0.0575, rowPickRate: 0.1584, avgOverflowPenalty: 8.3820, avgRowPickPenalty: 4.6980, avgOverflowGap: 15.0000, expectedPenalty: 1.2262, avgTurn: 6.9470 },
  { card: 38, overflowRate: 0.0505, rowPickRate: 0.1343, avgOverflowPenalty: 8.0548, avgRowPickPenalty: 4.8608, avgOverflowGap: 16.8904, expectedPenalty: 1.0595, avgTurn: 6.9585 },
  { card: 39, overflowRate: 0.0617, rowPickRate: 0.1158, avgOverflowPenalty: 8.3258, avgRowPickPenalty: 4.6108, avgOverflowGap: 15.5169, expectedPenalty: 1.0479, avgTurn: 6.9057 },
  { card: 40, overflowRate: 0.0540, rowPickRate: 0.1313, avgOverflowPenalty: 7.7037, avgRowPickPenalty: 4.7766, avgOverflowGap: 16.4691, expectedPenalty: 1.0433, avgTurn: 6.4953 },
  { card: 41, overflowRate: 0.0453, rowPickRate: 0.1093, avgOverflowPenalty: 7.4706, avgRowPickPenalty: 4.6951, avgOverflowGap: 16.0441, expectedPenalty: 0.8520, avgTurn: 6.9360 },
  { card: 42, overflowRate: 0.0548, rowPickRate: 0.1217, avgOverflowPenalty: 8.2439, avgRowPickPenalty: 4.7637, avgOverflowGap: 17.7805, expectedPenalty: 1.0314, avgTurn: 6.9499 },
  { card: 43, overflowRate: 0.0589, rowPickRate: 0.1065, avgOverflowPenalty: 8.1136, avgRowPickPenalty: 4.7610, avgOverflowGap: 17.6023, expectedPenalty: 0.9853, avgTurn: 6.8781 },
  { card: 44, overflowRate: 0.0655, rowPickRate: 0.1167, avgOverflowPenalty: 7.6733, avgRowPickPenalty: 4.2667, avgOverflowGap: 20.5248, expectedPenalty: 1.0006, avgTurn: 6.1141 },
  { card: 45, overflowRate: 0.0648, rowPickRate: 0.0838, avgOverflowPenalty: 8.2526, avgRowPickPenalty: 4.1626, avgOverflowGap: 19.6000, expectedPenalty: 0.8834, avgTurn: 6.6299 },
  { card: 46, overflowRate: 0.0632, rowPickRate: 0.0985, avgOverflowPenalty: 8.4737, avgRowPickPenalty: 4.3311, avgOverflowGap: 17.8105, expectedPenalty: 0.9621, avgTurn: 6.7412 },
  { card: 47, overflowRate: 0.0679, rowPickRate: 0.0846, avgOverflowPenalty: 8.1078, avgRowPickPenalty: 4.7717, avgOverflowGap: 16.8824, expectedPenalty: 0.9541, avgTurn: 6.7357 },
  { card: 48, overflowRate: 0.0729, rowPickRate: 0.0838, avgOverflowPenalty: 8.2830, avgRowPickPenalty: 4.7951, avgOverflowGap: 18.0094, expectedPenalty: 1.0055, avgTurn: 6.7058 },
  { card: 49, overflowRate: 0.0706, rowPickRate: 0.0658, avgOverflowPenalty: 8.0000, avgRowPickPenalty: 4.5729, avgOverflowGap: 18.9417, expectedPenalty: 0.8657, avgTurn: 6.6662 },
  { card: 50, overflowRate: 0.0716, rowPickRate: 0.0668, avgOverflowPenalty: 8.3524, avgRowPickPenalty: 4.5102, avgOverflowGap: 19.7905, expectedPenalty: 0.8991, avgTurn: 6.2877 },
  { card: 51, overflowRate: 0.0599, rowPickRate: 0.0639, avgOverflowPenalty: 8.0674, avgRowPickPenalty: 4.1263, avgOverflowGap: 19.7528, expectedPenalty: 0.7465, avgTurn: 6.4438 },
  { card: 52, overflowRate: 0.0719, rowPickRate: 0.0599, avgOverflowPenalty: 8.2778, avgRowPickPenalty: 4.3333, avgOverflowGap: 18.7130, expectedPenalty: 0.8543, avgTurn: 6.4338 },
  { card: 53, overflowRate: 0.0592, rowPickRate: 0.0473, avgOverflowPenalty: 8.4235, avgRowPickPenalty: 4.0294, avgOverflowGap: 20.2824, expectedPenalty: 0.6889, avgTurn: 6.3897 },
  { card: 54, overflowRate: 0.0763, rowPickRate: 0.0455, avgOverflowPenalty: 8.4386, avgRowPickPenalty: 3.7206, avgOverflowGap: 21.0351, expectedPenalty: 0.8133, avgTurn: 6.2878 },
  { card: 55, overflowRate: 0.0755, rowPickRate: 0.0578, avgOverflowPenalty: 8.3913, avgRowPickPenalty: 3.7955, avgOverflowGap: 25.8870, expectedPenalty: 0.8529, avgTurn: 5.3716 },
  { card: 56, overflowRate: 0.0920, rowPickRate: 0.0379, avgOverflowPenalty: 8.7721, avgRowPickPenalty: 3.9643, avgOverflowGap: 22.2426, expectedPenalty: 0.9574, avgTurn: 6.0568 },
  { card: 57, overflowRate: 0.0768, rowPickRate: 0.0398, avgOverflowPenalty: 8.5357, avgRowPickPenalty: 3.9655, avgOverflowGap: 23.7232, expectedPenalty: 0.8129, avgTurn: 6.1241 },
  { card: 58, overflowRate: 0.0857, rowPickRate: 0.0352, avgOverflowPenalty: 8.5000, avgRowPickPenalty: 3.9020, avgOverflowGap: 22.7339, expectedPenalty: 0.8659, avgTurn: 5.9350 },
  { card: 59, overflowRate: 0.0948, rowPickRate: 0.0327, avgOverflowPenalty: 8.5986, avgRowPickPenalty: 3.7959, avgOverflowGap: 22.0986, expectedPenalty: 0.9393, avgTurn: 5.8338 },
  { card: 60, overflowRate: 0.0914, rowPickRate: 0.0329, avgOverflowPenalty: 9.0662, avgRowPickPenalty: 3.6122, avgOverflowGap: 23.1912, expectedPenalty: 0.9476, avgTurn: 5.6190 },
  { card: 61, overflowRate: 0.0888, rowPickRate: 0.0386, avgOverflowPenalty: 8.8397, avgRowPickPenalty: 3.5965, avgOverflowGap: 22.9847, expectedPenalty: 0.9234, avgTurn: 5.7222 },
  { card: 62, overflowRate: 0.0930, rowPickRate: 0.0186, avgOverflowPenalty: 8.4519, avgRowPickPenalty: 4.1481, avgOverflowGap: 25.5333, expectedPenalty: 0.8635, avgTurn: 5.5899 },
  { card: 63, overflowRate: 0.1066, rowPickRate: 0.0109, avgOverflowPenalty: 8.9490, avgRowPickPenalty: 3.3750, avgOverflowGap: 24.2484, expectedPenalty: 0.9905, avgTurn: 5.6158 },
  { card: 64, overflowRate: 0.1044, rowPickRate: 0.0158, avgOverflowPenalty: 8.3750, avgRowPickPenalty: 3.5217, avgOverflowGap: 24.3355, expectedPenalty: 0.9299, avgTurn: 5.4712 },
  { card: 65, overflowRate: 0.1116, rowPickRate: 0.0180, avgOverflowPenalty: 8.3892, avgRowPickPenalty: 2.8889, avgOverflowGap: 25.6647, expectedPenalty: 0.9880, avgTurn: 5.1530 },
  { card: 66, overflowRate: 0.1150, rowPickRate: 0.0102, avgOverflowPenalty: 8.8402, avgRowPickPenalty: 3.0000, avgOverflowGap: 28.0237, expectedPenalty: 1.0469, avgTurn: 4.7585 },
  { card: 67, overflowRate: 0.1021, rowPickRate: 0.0162, avgOverflowPenalty: 8.8414, avgRowPickPenalty: 3.8696, avgOverflowGap: 27.3586, expectedPenalty: 0.9655, avgTurn: 5.1993 },
  { card: 68, overflowRate: 0.1132, rowPickRate: 0.0087, avgOverflowPenalty: 8.9231, avgRowPickPenalty: 2.5385, avgOverflowGap: 26.2367, expectedPenalty: 1.0322, avgTurn: 5.0482 },
  { card: 69, overflowRate: 0.1175, rowPickRate: 0.0074, avgOverflowPenalty: 8.6724, avgRowPickPenalty: 3.0909, avgOverflowGap: 28.9655, expectedPenalty: 1.0419, avgTurn: 4.8710 },
  { card: 70, overflowRate: 0.1268, rowPickRate: 0.0059, avgOverflowPenalty: 8.7969, avgRowPickPenalty: 2.4444, avgOverflowGap: 27.5729, expectedPenalty: 1.1301, avgTurn: 4.7232 },
  { card: 71, overflowRate: 0.1164, rowPickRate: 0.0087, avgOverflowPenalty: 8.8960, avgRowPickPenalty: 3.3846, avgOverflowGap: 25.0231, expectedPenalty: 1.0653, avgTurn: 4.7315 },
  { card: 72, overflowRate: 0.1362, rowPickRate: 0.0040, avgOverflowPenalty: 8.8276, avgRowPickPenalty: 3.1667, avgOverflowGap: 25.4532, expectedPenalty: 1.2154, avgTurn: 4.7644 },
  { card: 73, overflowRate: 0.1399, rowPickRate: 0.0048, avgOverflowPenalty: 9.1748, avgRowPickPenalty: 1.8571, avgOverflowGap: 29.5097, expectedPenalty: 1.2928, avgTurn: 4.7113 },
  { card: 74, overflowRate: 0.1299, rowPickRate: 0.0000, avgOverflowPenalty: 8.2650, avgRowPickPenalty: 0.0000, avgOverflowGap: 24.8950, expectedPenalty: 1.0734, avgTurn: 4.6981 },
  { card: 75, overflowRate: 0.1318, rowPickRate: 0.0026, avgOverflowPenalty: 9.1500, avgRowPickPenalty: 3.2500, avgOverflowGap: 29.1300, expectedPenalty: 1.2141, avgTurn: 4.4743 },
  { card: 76, overflowRate: 0.1349, rowPickRate: 0.0020, avgOverflowPenalty: 8.3632, avgRowPickPenalty: 3.3333, avgOverflowGap: 27.9900, expectedPenalty: 1.1349, avgTurn: 4.5611 },
  { card: 77, overflowRate: 0.1229, rowPickRate: 0.0020, avgOverflowPenalty: 8.8201, avgRowPickPenalty: 4.0000, avgOverflowGap: 30.9048, expectedPenalty: 1.0917, avgTurn: 4.1001 },
  { card: 78, overflowRate: 0.1436, rowPickRate: 0.0020, avgOverflowPenalty: 9.3649, avgRowPickPenalty: 3.3333, avgOverflowGap: 30.6919, expectedPenalty: 1.3519, avgTurn: 4.3764 },
  { card: 79, overflowRate: 0.1526, rowPickRate: 0.0013, avgOverflowPenalty: 8.6070, avgRowPickPenalty: 2.0000, avgOverflowGap: 29.6114, expectedPenalty: 1.3158, avgTurn: 4.3218 },
  { card: 80, overflowRate: 0.1461, rowPickRate: 0.0007, avgOverflowPenalty: 9.1831, avgRowPickPenalty: 1.0000, avgOverflowGap: 28.7277, expectedPenalty: 1.3422, avgTurn: 4.1831 },
  { card: 81, overflowRate: 0.1691, rowPickRate: 0.0000, avgOverflowPenalty: 9.1922, avgRowPickPenalty: 0.0000, avgOverflowGap: 25.2863, expectedPenalty: 1.5544, avgTurn: 4.1950 },
  { card: 82, overflowRate: 0.1492, rowPickRate: 0.0000, avgOverflowPenalty: 9.2982, avgRowPickPenalty: 0.0000, avgOverflowGap: 28.5132, expectedPenalty: 1.3874, avgTurn: 4.2899 },
  { card: 83, overflowRate: 0.1785, rowPickRate: 0.0000, avgOverflowPenalty: 8.8498, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.1612, expectedPenalty: 1.5801, avgTurn: 4.3669 },
  { card: 84, overflowRate: 0.1728, rowPickRate: 0.0000, avgOverflowPenalty: 9.1279, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.5504, expectedPenalty: 1.5774, avgTurn: 4.2405 },
  { card: 85, overflowRate: 0.1666, rowPickRate: 0.0000, avgOverflowPenalty: 9.0909, avgRowPickPenalty: 0.0000, avgOverflowGap: 27.3884, expectedPenalty: 1.5141, avgTurn: 4.0964 },
  { card: 86, overflowRate: 0.1552, rowPickRate: 0.0000, avgOverflowPenalty: 9.3991, avgRowPickPenalty: 0.0000, avgOverflowGap: 24.6842, expectedPenalty: 1.4588, avgTurn: 4.1654 },
  { card: 87, overflowRate: 0.1708, rowPickRate: 0.0000, avgOverflowPenalty: 9.1296, avgRowPickPenalty: 0.0000, avgOverflowGap: 30.0445, expectedPenalty: 1.5595, avgTurn: 4.0519 },
  { card: 88, overflowRate: 0.1855, rowPickRate: 0.0000, avgOverflowPenalty: 8.6996, avgRowPickPenalty: 0.0000, avgOverflowGap: 29.2418, expectedPenalty: 1.6135, avgTurn: 3.8329 },
  { card: 89, overflowRate: 0.1912, rowPickRate: 0.0000, avgOverflowPenalty: 9.2300, avgRowPickPenalty: 0.0000, avgOverflowGap: 25.5401, expectedPenalty: 1.7648, avgTurn: 4.1805 },
  { card: 90, overflowRate: 0.1816, rowPickRate: 0.0000, avgOverflowPenalty: 8.8993, avgRowPickPenalty: 0.0000, avgOverflowGap: 25.9173, expectedPenalty: 1.6159, avgTurn: 4.0568 },
  { card: 91, overflowRate: 0.2136, rowPickRate: 0.0000, avgOverflowPenalty: 9.3270, avgRowPickPenalty: 0.0000, avgOverflowGap: 25.5849, expectedPenalty: 1.9919, avgTurn: 4.2069 },
  { card: 92, overflowRate: 0.1809, rowPickRate: 0.0000, avgOverflowPenalty: 9.3383, avgRowPickPenalty: 0.0000, avgOverflowGap: 24.3829, expectedPenalty: 1.6893, avgTurn: 4.0894 },
  { card: 93, overflowRate: 0.2118, rowPickRate: 0.0000, avgOverflowPenalty: 9.4815, avgRowPickPenalty: 0.0000, avgOverflowGap: 26.8611, expectedPenalty: 2.0078, avgTurn: 4.1046 },
  { card: 94, overflowRate: 0.2174, rowPickRate: 0.0000, avgOverflowPenalty: 9.3106, avgRowPickPenalty: 0.0000, avgOverflowGap: 22.8385, expectedPenalty: 2.0243, avgTurn: 4.1668 },
  { card: 95, overflowRate: 0.2028, rowPickRate: 0.0000, avgOverflowPenalty: 9.3069, avgRowPickPenalty: 0.0000, avgOverflowGap: 20.6403, expectedPenalty: 1.8876, avgTurn: 4.2149 },
  { card: 96, overflowRate: 0.2287, rowPickRate: 0.0000, avgOverflowPenalty: 9.1740, avgRowPickPenalty: 0.0000, avgOverflowGap: 20.9233, expectedPenalty: 2.0985, avgTurn: 4.2375 },
  { card: 97, overflowRate: 0.2105, rowPickRate: 0.0000, avgOverflowPenalty: 8.9935, avgRowPickPenalty: 0.0000, avgOverflowGap: 22.2435, expectedPenalty: 1.8934, avgTurn: 4.2078 },
  { card: 98, overflowRate: 0.2329, rowPickRate: 0.0000, avgOverflowPenalty: 9.1657, avgRowPickPenalty: 0.0000, avgOverflowGap: 19.7714, expectedPenalty: 2.1344, avgTurn: 4.3014 },
  { card: 99, overflowRate: 0.2245, rowPickRate: 0.0000, avgOverflowPenalty: 8.8220, avgRowPickPenalty: 0.0000, avgOverflowGap: 19.2315, expectedPenalty: 1.9807, avgTurn: 4.2005 },
  { card: 100, overflowRate: 0.2285, rowPickRate: 0.0000, avgOverflowPenalty: 9.6925, avgRowPickPenalty: 0.0000, avgOverflowGap: 20.5224, expectedPenalty: 2.2149, avgTurn: 4.3683 },
  { card: 101, overflowRate: 0.2203, rowPickRate: 0.0000, avgOverflowPenalty: 9.7024, avgRowPickPenalty: 0.0000, avgOverflowGap: 16.5119, expectedPenalty: 2.1377, avgTurn: 4.3692 },
  { card: 102, overflowRate: 0.2149, rowPickRate: 0.0000, avgOverflowPenalty: 9.4038, avgRowPickPenalty: 0.0000, avgOverflowGap: 17.0577, expectedPenalty: 2.0207, avgTurn: 4.5152 },
  { card: 103, overflowRate: 0.2025, rowPickRate: 0.0000, avgOverflowPenalty: 9.1107, avgRowPickPenalty: 0.0000, avgOverflowGap: 14.8111, expectedPenalty: 1.8450, avgTurn: 4.5343 },
  { card: 104, overflowRate: 0.1982, rowPickRate: 0.0000, avgOverflowPenalty: 9.3633, avgRowPickPenalty: 0.0000, avgOverflowGap: 13.0933, expectedPenalty: 1.8554, avgTurn: 4.6585 },
];

/** Per-turn board state baselines (index 0 = turn 1, index 9 = turn 10). */
export const TURN_BASELINE: readonly TurnBaseline[] = [
  { turn: 1, avgMinRowTop: 21.2524, minRowTopP50: 17, avgPrimedRows: 0.0000, avgMaxRowLen: 1.0000 },
  { turn: 2, avgMinRowTop: 21.6065, minRowTopP50: 16, avgPrimedRows: 0.2676, avgMaxRowLen: 3.6475 },
  { turn: 3, avgMinRowTop: 24.0365, minRowTopP50: 16, avgPrimedRows: 0.6837, avgMaxRowLen: 4.3112 },
  { turn: 4, avgMinRowTop: 32.8486, minRowTopP50: 23, avgPrimedRows: 1.1123, avgMaxRowLen: 4.6085 },
  { turn: 5, avgMinRowTop: 44.6827, minRowTopP50: 45, avgPrimedRows: 1.4158, avgMaxRowLen: 4.7421 },
  { turn: 6, avgMinRowTop: 49.7699, minRowTopP50: 54, avgPrimedRows: 1.6446, avgMaxRowLen: 4.7944 },
  { turn: 7, avgMinRowTop: 51.5775, minRowTopP50: 55, avgPrimedRows: 1.8283, avgMaxRowLen: 4.8257 },
  { turn: 8, avgMinRowTop: 50.0181, minRowTopP50: 51, avgPrimedRows: 1.9584, avgMaxRowLen: 4.8473 },
  { turn: 9, avgMinRowTop: 46.9025, minRowTopP50: 48, avgPrimedRows: 1.9128, avgMaxRowLen: 4.8457 },
  { turn: 10, avgMinRowTop: 42.6782, minRowTopP50: 42, avgPrimedRows: 1.7944, avgMaxRowLen: 4.8047 },
];

/** Number of games used to generate this prior. */
export const PRIOR_GAMES = 780;
